# Generated by Django 5.1.6 on 2025-03-13 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HotelPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('STANDARD', 'Standard'), ('DELUXE', 'Deluxe'), ('SUPER DELUXE', 'Super Deluxe')], max_length=20, unique=True)),
                ('room_price', models.PositiveIntegerField()),
                ('extra_bed_price', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TransportPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transport_type', models.CharField(choices=[('SEDAN', 'Sedan'), ('SUV', 'SUV'), ('TEMPO 14', 'Tempo 14'), ('TEMPO 17', 'Tempo 17')], max_length=20, unique=True)),
                ('price_per_day', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='VolvoPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('volvo_type', models.CharField(choices=[('1 SIDE', 'One Side'), ('BOTH SIDE', 'Both Side')], max_length=20, unique=True)),
                ('price_per_pax', models.PositiveIntegerField()),
            ],
        ),
    ]
