# Generated by Django 5.1.6 on 2025-03-13 07:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_delete_rate'),
    ]

    operations = [
        migrations.CreateModel(
            name='TripPlace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='TripPlacePricing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('STANDARD_ROOM_PRICE', models.PositiveIntegerField(default=2000)),
                ('DELUXE_ROOM_PRICE', models.PositiveIntegerField(default=3000)),
                ('SUPER_DELUXE_ROOM_PRICE', models.PositiveIntegerField(default=4500)),
                ('STANDARD_EXTRA_BED_PRICE', models.PositiveIntegerField(default=800)),
                ('DELUXE_EXTRA_BED_PRICE', models.PositiveIntegerField(default=1000)),
                ('SUPER_DELUXE_EXTRA_BED_PRICE', models.PositiveIntegerField(default=1500)),
                ('SEDAN_PRICE', models.PositiveIntegerField(default=3500)),
                ('SUV_PRICE', models.PositiveIntegerField(default=5500)),
                ('TEMPO_14_PRICE', models.PositiveIntegerField(default=6500)),
                ('TEMPO_17_PRICE', models.PositiveIntegerField(default=7000)),
                ('VOLVO_1_SIDE_PRICE', models.PositiveIntegerField(default=1000)),
                ('VOLVO_BOTH_SIDE_PRICE', models.PositiveIntegerField(default=2000)),
                ('trip_place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.tripplace')),
            ],
        ),
    ]
