# Generated by Django 5.1.6 on 2025-03-13 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_tripplace_tripplacepricing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tripplacepricing',
            name='DELUXE_EXTRA_BED_PRICE',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='tripplacepricing',
            name='DELUXE_ROOM_PRICE',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='tripplacepricing',
            name='SEDAN_PRICE',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='tripplacepricing',
            name='STANDARD_EXTRA_BED_PRICE',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='tripplacepricing',
            name='STANDARD_ROOM_PRICE',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='tripplacepricing',
            name='SUPER_DELUXE_EXTRA_BED_PRICE',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='tripplacepricing',
            name='SUPER_DELUXE_ROOM_PRICE',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='tripplacepricing',
            name='SUV_PRICE',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='tripplacepricing',
            name='TEMPO_14_PRICE',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='tripplacepricing',
            name='TEMPO_17_PRICE',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='tripplacepricing',
            name='VOLVO_1_SIDE_PRICE',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='tripplacepricing',
            name='VOLVO_BOTH_SIDE_PRICE',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
