# Generated by Django 5.1.6 on 2025-03-14 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_alter_tripplace_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tripplacepricing',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
