# Generated by Django 5.1.6 on 2025-03-15 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_remove_tripplacepricing_date_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tripplacepricing',
            options={'verbose_name': 'Destination Price', 'verbose_name_plural': 'Destination Prices'},
        ),
        migrations.AddField(
            model_name='tripplacepricing',
            name='month',
            field=models.PositiveIntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12)], null=True),
        ),
        migrations.AddField(
            model_name='tripplacepricing',
            name='year',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tripplacepricing',
            name='end_date',
            field=models.DateField(verbose_name='Price Valid To'),
        ),
        migrations.AlterField(
            model_name='tripplacepricing',
            name='start_date',
            field=models.DateField(verbose_name='Price Valid From'),
        ),
        migrations.AlterUniqueTogether(
            name='tripplacepricing',
            unique_together={('trip_place', 'month', 'year')},
        ),
    ]
